services:
  aio-sandbox:
    container_name: aio-sandbox
    image: enterprise-public-cn-beijing.cr.volces.com/vefaas-public/all-in-one-sandbox:latest
    ports:
      - "8022:8080" # Sandbox MCP 端点：http://localhost:8022/mcp
    volumes:
      - ./src/skills:/mnt/skills:ro
      - ./data/workspace:/workspace:rw
      - ./data/cron:/workspace/cron:rw
    environment:
      HTTP_PROXY: "http://host.lima.internal:7897"
      HTTPS_PROXY: "http://host.lima.internal:7897"
      ALL_PROXY: "socks5://host.lima.internal:7897"
      NO_PROXY: "localhost,127.0.0.1,::1,host.lima.internal"
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
